// Database types — generated by: npx supabase gen types typescript --linked
// Bridged 2026-06-02: added 9 missing tables actively used by the application.
// TODO: Run actual generation: npx supabase login && npx supabase link && npx supabase gen types typescript --linked > src/types/database.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      // ─── Core (original) ───

      organizations: {
        Row: {
          id: string;
          name: string;
          logo_url: string | null;
          brand_color: string | null;
          stripe_account_id: string | null;
          plan: string;
          iban: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          logo_url?: string | null;
          brand_color?: string | null;
          stripe_account_id?: string | null;
          plan?: string;
          iban?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          logo_url?: string | null;
          brand_color?: string | null;
          stripe_account_id?: string | null;
          plan?: string;
          iban?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };

      org_members: {
        Row: {
          id: string;
          org_id: string;
          user_id: string;
          role: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          user_id: string;
          role?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          user_id?: string;
          role?: string;
          created_at?: string;
        };
      };

      clients: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          email: string;
          vat_number: string | null;
          address: string | null;
          currency: string;
          phone: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          name: string;
          email: string;
          vat_number?: string | null;
          address?: string | null;
          currency?: string;
          phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          name?: string;
          email?: string;
          vat_number?: string | null;
          address?: string | null;
          currency?: string;
          phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };

      invoices: {
        Row: {
          id: string;
          org_id: string;
          client_id: string;
          number: string;
          status: string;
          issue_date: string;
          due_date: string;
          subtotal: number;
          tax_rate: number;
          withholding_tax_rate: number;
          total: number;
          currency: string;
          payment_link: string | null;
          paid_at: string | null;
          notes: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          client_id: string;
          number: string;
          status?: string;
          issue_date: string;
          due_date: string;
          subtotal: number;
          tax_rate?: number;
          withholding_tax_rate?: number;
          total: number;
          currency?: string;
          payment_link?: string | null;
          paid_at?: string | null;
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          client_id?: string;
          number?: string;
          status?: string;
          issue_date?: string;
          due_date?: string;
          subtotal?: number;
          tax_rate?: number;
          withholding_tax_rate?: number;
          total?: number;
          currency?: string;
          payment_link?: string | null;
          paid_at?: string | null;
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };

      invoice_items: {
        Row: {
          id: string;
          invoice_id: string;
          description: string;
          quantity: number;
          unit_price: number;
          tax_rate: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          description: string;
          quantity: number;
          unit_price: number;
          tax_rate?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          description?: string;
          quantity?: number;
          unit_price?: number;
          tax_rate?: number;
          created_at?: string;
        };
      };

      invoice_events: {
        Row: {
          id: string;
          invoice_id: string;
          event_type: string;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          event_type: string;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          event_type?: string;
          metadata?: Json | null;
          created_at?: string;
        };
      };

      user_push_tokens: {
        Row: {
          id: string;
          user_id: string;
          token: string;
          platform: "android" | "ios";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          token: string;
          platform: "android" | "ios";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          token?: string;
          platform?: "android" | "ios";
          updated_at?: string;
        };
      };

      payment_audit_logs: {
        Row: {
          id: string;
          event_type: string;
          provider: "stripe" | "revenuecat";
          invoice_id: string | null;
          org_id: string | null;
          external_event_id: string | null;
          environment: "sandbox" | "production" | "unknown";
          outcome: "success" | "failure" | "ignored";
          error_code: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_type: string;
          provider: "stripe" | "revenuecat";
          invoice_id?: string | null;
          org_id?: string | null;
          external_event_id?: string | null;
          environment: "sandbox" | "production" | "unknown";
          outcome: "success" | "failure" | "ignored";
          error_code?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_type?: string;
          provider?: "stripe" | "revenuecat";
          invoice_id?: string | null;
          org_id?: string | null;
          external_event_id?: string | null;
          environment?: "sandbox" | "production" | "unknown";
          outcome?: "success" | "failure" | "ignored";
          error_code?: string | null;
        };
      };

      // ─── Added 2026-06-02: tables used by the app but missing from types ───

      audit_logs: {
        Row: {
          id: string;
          org_id: string;
          user_id: string;
          action: string;
          entity_type: string;
          entity_id: string;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          user_id: string;
          action: string;
          entity_type: string;
          entity_id: string;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          user_id?: string;
          action?: string;
          entity_type?: string;
          entity_id?: string;
          metadata?: Json | null;
        };
      };

      payment_tokens: {
        Row: {
          id: string;
          invoice_id: string;
          token_hash: string;
          expires_at: string;
          consumed: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          token_hash: string;
          expires_at: string;
          consumed?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          token_hash?: string;
          expires_at?: string;
          consumed?: boolean;
        };
      };

      reminders: {
        Row: {
          id: string;
          invoice_id: string;
          org_id: string;
          type: string;
          sent_at: string | null;
          scheduled_for: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          org_id: string;
          type: string;
          sent_at?: string | null;
          scheduled_for: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          org_id?: string;
          type?: string;
          sent_at?: string | null;
          scheduled_for?: string;
        };
      };

      org_credits: {
        Row: {
          id: string;
          org_id: string;
          earned_credits: number;
          consumed_credits: number;
          daily_earned_credits: number;
          daily_period_date: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          earned_credits?: number;
          consumed_credits?: number;
          daily_earned_credits?: number;
          daily_period_date?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          earned_credits?: number;
          consumed_credits?: number;
          daily_earned_credits?: number;
          daily_period_date?: string;
          updated_at?: string;
        };
      };

      ad_impressions: {
        Row: {
          id: string;
          org_id: string;
          user_id: string;
          ad_provider: string;
          ad_unit_id: string;
          reward_amount: number;
          reward_type: string | null;
          verification_hash: string;
          claimed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          user_id: string;
          ad_provider: string;
          ad_unit_id: string;
          reward_amount: number;
          reward_type?: string | null;
          verification_hash: string;
          claimed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          user_id?: string;
          ad_provider?: string;
          ad_unit_id?: string;
          reward_amount?: number;
          reward_type?: string | null;
          verification_hash?: string;
        };
      };

      credit_transactions: {
        Row: {
          id: string;
          org_id: string;
          type: "earn" | "consume" | "expire";
          amount: number;
          source: string;
          reference_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          type: "earn" | "consume" | "expire";
          amount: number;
          source: string;
          reference_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          type?: "earn" | "consume" | "expire";
          amount?: number;
          source?: string;
          reference_id?: string;
        };
      };

      rewarded_ad_config: {
        Row: {
          id: string;
          max_rewarded_invoices_month: number;
          max_daily_rewarded: number;
          cooldown_minutes: number;
          updated_at: string;
        };
        Insert: {
          id?: string;
          max_rewarded_invoices_month?: number;
          max_daily_rewarded?: number;
          cooldown_minutes?: number;
          updated_at?: string;
        };
        Update: {
          id?: string;
          max_rewarded_invoices_month?: number;
          max_daily_rewarded?: number;
          cooldown_minutes?: number;
          updated_at?: string;
        };
      };

      revenue_events: {
        Row: {
          id: string;
          org_id: string;
          revenue_source: "subscription" | "commission" | "ad_reward";
          amount: number;
          currency: string;
          provider_event_id: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          revenue_source: "subscription" | "commission" | "ad_reward";
          amount: number;
          currency?: string;
          provider_event_id?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          revenue_source?: "subscription" | "commission" | "ad_reward";
          amount?: number;
          currency?: string;
          provider_event_id?: string | null;
          metadata?: Json | null;
        };
      };

      admob_reconciliation_results: {
        Row: {
          id: string;
          reconciliation_date: string;
          ad_unit_id: string;
          reported_impressions: number;
          verified_impressions: number;
          discrepancy: number;
          status: "ok" | "discrepancy" | "error";
          details: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          reconciliation_date: string;
          ad_unit_id: string;
          reported_impressions: number;
          verified_impressions: number;
          discrepancy: number;
          status: "ok" | "discrepancy" | "error";
          details?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          reconciliation_date?: string;
          ad_unit_id?: string;
          reported_impressions?: number;
          verified_impressions?: number;
          discrepancy?: number;
          status?: "ok" | "discrepancy" | "error";
          details?: Json | null;
        };
      };

      // ─── Future: tables for new domain models (not yet in DB) ───

      recovery_campaigns: {
        Row: {
          id: string;
          org_id: string;
          invoice_id: string;
          current_stage: string;
          started_at: string;
          next_action_at: string | null;
          resolved_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          invoice_id: string;
          current_stage?: string;
          started_at?: string;
          next_action_at?: string | null;
          resolved_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          invoice_id?: string;
          current_stage?: string;
          next_action_at?: string | null;
          resolved_at?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
      };

      recovery_actions: {
        Row: {
          id: string;
          campaign_id: string;
          stage: string;
          action_type: string;
          sent_at: string | null;
          delivered_at: string | null;
          opened_at: string | null;
          error: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          stage: string;
          action_type: string;
          sent_at?: string | null;
          delivered_at?: string | null;
          opened_at?: string | null;
          error?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          stage?: string;
          action_type?: string;
          sent_at?: string | null;
          delivered_at?: string | null;
          opened_at?: string | null;
          error?: string | null;
        };
      };

      ai_recommendations: {
        Row: {
          id: string;
          org_id: string;
          type: string;
          priority: string;
          title: string;
          description: string;
          action_label: string | null;
          action_route: string | null;
          metadata: Json | null;
          dismissed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          type: string;
          priority?: string;
          title: string;
          description: string;
          action_label?: string | null;
          action_route?: string | null;
          metadata?: Json | null;
          dismissed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          type?: string;
          priority?: string;
          title?: string;
          description?: string;
          action_label?: string | null;
          action_route?: string | null;
          metadata?: Json | null;
          dismissed_at?: string | null;
        };
      };

      signatures: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          type: string;
          svg_data: string | null;
          image_base64: string | null;
          is_default: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          name: string;
          type: string;
          svg_data?: string | null;
          image_base64?: string | null;
          is_default?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          name?: string;
          type?: string;
          svg_data?: string | null;
          image_base64?: string | null;
          is_default?: boolean;
        };
      };

      invoice_templates: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          is_default: boolean;
          layout: string;
          color_scheme: string;
          primary_color: string;
          accent_color: string;
          show_logo: boolean;
          logo_position: string;
          logo_max_height: number;
          font_family: string;
          font_size_body: number;
          font_size_heading: number;
          show_sender_details: boolean;
          show_client_details: boolean;
          show_payment_terms: boolean;
          show_notes: boolean;
          show_thank_you: boolean;
          thank_you_message: string | null;
          signature_position: string;
          custom_fields: Json | null;
          footer_text: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          name: string;
          is_default?: boolean;
          layout?: string;
          color_scheme?: string;
          primary_color?: string;
          accent_color?: string;
          show_logo?: boolean;
          logo_position?: string;
          logo_max_height?: number;
          font_family?: string;
          font_size_body?: number;
          font_size_heading?: number;
          show_sender_details?: boolean;
          show_client_details?: boolean;
          show_payment_terms?: boolean;
          show_notes?: boolean;
          show_thank_you?: boolean;
          thank_you_message?: string | null;
          signature_position?: string;
          custom_fields?: Json | null;
          footer_text?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          name?: string;
          is_default?: boolean;
          layout?: string;
          color_scheme?: string;
          primary_color?: string;
          accent_color?: string;
          show_logo?: boolean;
          logo_position?: string;
          logo_max_height?: number;
          font_family?: string;
          font_size_body?: number;
          font_size_heading?: number;
          show_sender_details?: boolean;
          show_client_details?: boolean;
          show_payment_terms?: boolean;
          show_notes?: boolean;
          show_thank_you?: boolean;
          thank_you_message?: string | null;
          signature_position?: string;
          custom_fields?: Json | null;
          footer_text?: string | null;
          updated_at?: string;
        };
      };
    };

    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
