// Database types — generated by: npx supabase gen types typescript --linked
// TODO: Replace with actual generated types after Supabase project is created.
// Run: npx supabase login && npx supabase link --project-ref <ref> && npx supabase gen types typescript --linked > src/types/database.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          logo_url: string | null;
          brand_color: string | null;
          stripe_account_id: string | null;
          plan: string;
          iban: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          logo_url?: string | null;
          brand_color?: string | null;
          stripe_account_id?: string | null;
          plan?: string;
          iban?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          logo_url?: string | null;
          brand_color?: string | null;
          stripe_account_id?: string | null;
          plan?: string;
          iban?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      org_members: {
        Row: {
          id: string;
          org_id: string;
          user_id: string;
          role: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          user_id: string;
          role?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          user_id?: string;
          role?: string;
          created_at?: string;
        };
      };
      clients: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          email: string;
          vat_number: string | null;
          address: string | null;
          currency: string;
          phone: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          name: string;
          email: string;
          vat_number?: string | null;
          address?: string | null;
          currency?: string;
          phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          name?: string;
          email?: string;
          vat_number?: string | null;
          address?: string | null;
          currency?: string;
          phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          org_id: string;
          client_id: string;
          number: string;
          status: string;
          issue_date: string;
          due_date: string;
          subtotal: number;
          tax_rate: number;
          withholding_tax_rate: number;
          total: number;
          currency: string;
          payment_link: string | null;
          paid_at: string | null;
          notes: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          client_id: string;
          number: string;
          status?: string;
          issue_date: string;
          due_date: string;
          subtotal: number;
          tax_rate?: number;
          withholding_tax_rate?: number;
          total: number;
          currency?: string;
          payment_link?: string | null;
          paid_at?: string | null;
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          client_id?: string;
          number?: string;
          status?: string;
          issue_date?: string;
          due_date?: string;
          subtotal?: number;
          tax_rate?: number;
          withholding_tax_rate?: number;
          total?: number;
          currency?: string;
          payment_link?: string | null;
          paid_at?: string | null;
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoice_items: {
        Row: {
          id: string;
          invoice_id: string;
          description: string;
          quantity: number;
          unit_price: number;
          tax_rate: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          description: string;
          quantity: number;
          unit_price: number;
          tax_rate?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          description?: string;
          quantity?: number;
          unit_price?: number;
          tax_rate?: number;
          created_at?: string;
        };
      };
      invoice_events: {
        Row: {
          id: string;
          invoice_id: string;
          event_type: string;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          event_type: string;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          event_type?: string;
          metadata?: Json | null;
          created_at?: string;
        };
      };
      user_push_tokens: {
        Row: {
          id: string;
          user_id: string;
          token: string;
          platform: "android" | "ios";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          token: string;
          platform: "android" | "ios";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          token?: string;
          platform?: "android" | "ios";
          updated_at?: string;
        };
      };
      payment_audit_logs: {
        Row: {
          id: string;
          event_type: string;
          provider: "stripe" | "revenuecat";
          invoice_id: string | null;
          org_id: string | null;
          external_event_id: string | null;
          environment: "sandbox" | "production" | "unknown";
          outcome: "success" | "failure" | "ignored";
          error_code: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_type: string;
          provider: "stripe" | "revenuecat";
          invoice_id?: string | null;
          org_id?: string | null;
          external_event_id?: string | null;
          environment: "sandbox" | "production" | "unknown";
          outcome: "success" | "failure" | "ignored";
          error_code?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_type?: string;
          provider?: "stripe" | "revenuecat";
          invoice_id?: string | null;
          org_id?: string | null;
          external_event_id?: string | null;
          environment?: "sandbox" | "production" | "unknown";
          outcome?: "success" | "failure" | "ignored";
          error_code?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
