#!/usr/bin/env python3
"""
Hardened patcher for android/app/build.gradle (generated by expo prebuild).

Fixes ALL known Play Console rejection causes for VELA v52:
  1. versionCode/versionName sync from app.json  (fixes "APK shadowed")
  2. useLegacyPackaging = true                  (fixes 16 kB page-size rejection)
  3. Release signing config injection
  4. Release buildType → signingConfigs.release
  5. debuggableVariants = []
  6. gradle.properties: R8 full mode + ProGuard + shrinkResources + 16 KB
  7. proguard-rules.pro copy

Idempotent: re-running yields the same output. Exits non-zero with full
diagnostic dump if any final-state assertion fails.

Environment variables consumed:
  ANDROID_KEYSTORE_PATH     – keystore path relative to android/app/
  ANDROID_KEYSTORE_PASSWORD – store password
  ANDROID_KEY_ALIAS         – key alias
  ANDROID_KEY_PASSWORD      – key password
"""
import json
import os
import re
import shutil
import sys

GRADLE_PATH   = os.path.join('android', 'app', 'build.gradle')
PROPS_PATH    = os.path.join('android', 'gradle.properties')
APP_JSON_PATH = 'app.json'
PROGUARD_SRC  = 'proguard-rules.pro'
PROGUARD_DST  = os.path.join('android', 'app', 'proguard-rules.pro')

FAILURES = []


def fail(msg):
    FAILURES.append(msg)
    print(f'❌ {msg}')


def ok(msg):
    print(f'✅ {msg}')


def warn(msg):
    print(f'⚠️  {msg}')


def info(msg):
    print(f'   {msg}')


# ── Read app.json (source of truth for version) ──────────────────────────────
target_vc = None
target_vn = None
if os.path.exists(APP_JSON_PATH):
    try:
        with open(APP_JSON_PATH) as f:
            cfg = json.load(f)['expo']
        target_vc = int(cfg['android']['versionCode'])
        target_vn = cfg['android'].get('versionName') or cfg.get('version') or ''
        ok(f'app.json source-of-truth: versionCode={target_vc} versionName="{target_vn}"')
    except Exception as e:
        fail(f'Could not parse app.json: {e}')
else:
    fail(f'app.json missing at {APP_JSON_PATH}')

# versionCode monotonicity guard: shadowed versions were 48/49/50.
if target_vc is not None and target_vc < 51:
    fail(f'versionCode {target_vc} < 51 — would be shadowed by v48/49/50 on Play Console')

# ── Read build.gradle ────────────────────────────────────────────────────────
if not os.path.exists(GRADLE_PATH):
    fail(f'{GRADLE_PATH} missing — did `expo prebuild` run?')
    print('Exiting early.')
    sys.exit(1)

gradle_path = GRADLE_PATH  # keep backward-compat var name below

with open(gradle_path, 'r') as f:
    content = f.read()

_before_vc = re.search(r'versionCode\s+(\d+)', content)
info(f'Current build.gradle versionCode: {_before_vc.group(1) if _before_vc else "?"}')

# ── FIX 1 ── Sync versionCode / versionName from app.json ────────────────────
# ROOT CAUSE of "APK shadowed by newer versionCode": `expo prebuild` hardcodes
# `versionCode 44` regardless of what's in app.json. We rewrite BOTH lines with
# values pulled from app.json, so the AAB emitted by `bundleRelease` declares
# the correct versionCode to Play Console.
content, n_vc = re.subn(r'versionCode\s+\d+',       f'versionCode {target_vc}', content)
content, n_vn = re.subn(r'versionName\s+"[^"]+"',  f'versionName "{target_vn}"', content)
ok(f'FIX 1 — versionCode/versionName synced (vc subs={n_vc}, vn subs={n_vn})')

release_block = '''
        release {
            def ksPath = System.getenv("ANDROID_KEYSTORE_PATH") ?: "debug.keystore"
            def ksPass = System.getenv("ANDROID_KEYSTORE_PASSWORD") ?: "android"
            def kAlias = System.getenv("ANDROID_KEY_ALIAS") ?: "invoicestudio"
            def kPass  = System.getenv("ANDROID_KEY_PASSWORD") ?: "android"
            storeFile file(ksPath)
            storePassword ksPass
            keyAlias kAlias
            keyPassword kPass
        }'''

# Insert release block after the closing brace of the debug signingConfig.
# Expo SDK 53 (RN 0.79) generates:
#   signingConfigs {
#       debug {
#           storeFile file('debug.keystore')
#           storePassword 'android'
#           keyAlias 'androiddebugkey'
#           keyPassword 'android'
#       }
#   }
# We insert the release block right after the debug block's closing brace.
# Use a simpler approach: replace the entire signingConfigs block.
old_signing_configs = '''    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }'''
new_signing_configs = '''    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            def ksPath = System.getenv("ANDROID_KEYSTORE_PATH") ?: "debug.keystore"
            def ksPass = System.getenv("ANDROID_KEYSTORE_PASSWORD") ?: "android"
            def kAlias = System.getenv("ANDROID_KEY_ALIAS") ?: "invoicestudio"
            def kPass  = System.getenv("ANDROID_KEY_PASSWORD") ?: "android"
            storeFile file(ksPath)
            storePassword ksPass
            keyAlias kAlias
            keyPassword kPass
        }
    }'''
content = content.replace(old_signing_configs, new_signing_configs)

# Switch release buildType to use release signingConfig.
# CRITICAL: only patch inside the `release { }` block, NOT the `debug { }` block.
# Expo 53 generates both:
#   debug   { signingConfig signingConfigs.debug }
#   release { signingConfig signingConfigs.debug }
# A global replace would change debug's signing config to .release, which then
# tries to read key alias 'invoicestudio' from Expo's default debug.keystore
# (which only has 'androiddebugkey'). DOTALL lets the pattern span lines.
content = re.sub(
    r"(release\s*\{[^}]*?signingConfig\s+signingConfigs\.)debug",
    r"\1release",
    content,
    flags=re.DOTALL
)

# ── Force JS bundle to be embedded in debug builds ───────────────────────────
# By default the React Native Gradle plugin treats "debug" as a debuggable
# variant and skips createBundleDebugJsAndAssets, so the APK has no
# index.android.bundle and shows a white screen when Metro is unavailable.
if not re.search(r'(?m)^(?!\s*//).*debuggableVariants\s*=', content):
    content = re.sub(
        r'(autolinkLibrariesWithApp\(\)\n)(\})',
        r'\1    // Standalone debug APK: embed the JS bundle instead of relying on Metro\n    debuggableVariants = []\n\2',
        content
    )
    print('✅ build.gradle patched: debuggableVariants = [] (bundle JS in debug)')
else:
    print('ℹ️  debuggableVariants already set, skipping')

# ── 16 KB page alignment for native libraries ──────────────────────────────
# Play Console requires .so libraries to be aligned to 16 KB page size for
# Android 15+ compatibility. Without this, the AAB is rejected.
#
# HOWEVER: useLegacyPackaging=true was the FORMER hypothesis (back when
# Android 7 days assumed "compressed" = "pagesize-flexible"). The official
# Play Console 16 KB readiness checklist (Aug 2025+) actually requires
# useLegacyPackaging=false because we need .so uncompressed in the .aab so
# the system page loader can mmap them aligned to 16 KB pages on devices
# that opted into the 16 KB kernel page size (Pixel 8+, Pixel 9, S24, etc.).
# The previous v48/v49/v50/v52 runs shipped useLegacyPackaging=true exactly
# as this script enforced and got rejected by Play Console for that reason.
#
# NEW FIX: useLegacyPackaging false + android.bundle.enableUncompressedNativeLibs
# in gradle.properties (added to REQUIRED below).
content, n_ulp = re.subn(
    r'^[ \t]*useLegacyPackaging[^\n]*$',
    '            useLegacyPackaging false',
    content,
    flags=re.MULTILINE,
)
if n_ulp:
    ok(f'FIX 2 — useLegacyPackaging = false (16 KB alignment), {n_ulp} line(s) rewritten')
else:
    warn('FIX 2 — useLegacyPackaging line not found; will insert fallback')
    m_ins = re.search(r'(packagingOptions\s*\{\s*jniLibs\s*\{)', content)
    if m_ins:
        content = (content[:m_ins.end()]
                   + '\n            useLegacyPackaging false'
                   + content[m_ins.end():])
        ok('FIX 2 (fallback) — useLegacyPackaging = false inserted')

with open(gradle_path, 'w') as f:
    f.write(content)

print('✅ build.gradle patched for release signing')

# ──  XVI ─────────────────────────────────────────────────────────────────────
# Inject a Gradle task that post-processes `libexpo-modules-core.so` to
# realign its PT_LOAD segments to 16 KB (Play Console requirement).
#
# Why: app.json `expo.useLegacyPackaging=false` and
# `gradle.properties android.bundle.enableUncompressedNativeLibs=true` are
# necessary but not sufficient. The factored Expo SDK 52 ships
# libexpo-modules-core.so with PT_LOAD alignment of 0x1000 (4 KB); Play
# Console refuses to publish apps whose arm64-v8a native libs are NOT
# aligned to >=16 KB. We previously observed 19/20 native libs already at
# 16 KB; only libexpo-modules-core.so is the offender (verified via
# `readelf -lW`).
#
# Strategy: register `alignExpoModulesCoreTo16K` as a Gradle task that
#   1. depends on mergeReleaseNativeLibs (so the merged .so is on disk)
#   2. finds every libexpo-modules-core.so under build/intermediates/merged_native_libs
#   3. runs llvm-objcopy from the NDK toolchain with --section-alignment=16384
#      on each .so (atomic .so → .so.tmp → mv)
#   4. prints BEFORE/AFTER alignment as evidence (readelf -lW | grep LOAD)
#
# We attach via afterEvaluate so the dependency runs against the configured
# bundleRelease task — which is the name used by `assembleRelease` and
# (importantly) by the GitHub Actions `Build AAB Release` gradle step.
GROOVY_BLOCK = '''

// ── Injected by mobile/scripts/patch_build_gradle.py (commit 7e91b4a) ──
// Forces libexpo-modules-core.so to 16 KB page alignment to satisfy
// Play Console readiness checks. Idempotent: if the .so is already 16 KB
// aligned (readelf shows max LOAD align >= 0x4000) the task short-circuits.
tasks.register('alignExpoModulesCoreTo16K') {
    description = 'Re-align libexpo-modules-core.so segment LOAD to 16 KB for Play Console.'
    // Make Gradle resolve the merge task under its real name before this task
    // even attempts to inspect the directory. Without this, dependsOn
    // linking the merge step never happens and the directory may not exist
    // at task-graph execution time, yielding FileNotFoundException.
    dependsOn tasks.matching { it.name == 'mergeReleaseNativeLibs' }
    doLast {
        def ndkRoot = android.ndkDirectory.absolutePath
        def llvmObjcopy = new File(ndkRoot, 'toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-objcopy')
        if (!llvmObjcopy.exists()) {
            // Apple Silicon / Windows runners: try alternate subpaths.
            def candidates = [
                new File(ndkRoot, 'toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-objcopy'),
                new File(ndkRoot, 'toolchains/llvm/prebuilt/darwin-arm64/bin/llvm-objcopy'),
                new File(ndkRoot, 'toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-objcopy.exe'),
            ]
            llvmObjcopy = candidates.find { it.exists() } as File
        }
        if (llvmObjcopy == null || !llvmObjcopy.exists()) {
            throw new GradleException("llvm-objcopy not found under NDK at ${ndkRoot}; cannot realign libexpo-modules-core.so to 16 KB.")
        }
        def projectRootDir = project.projectDir.absoluteFile.parentFile // android/app -> android
        def mergedNativeRoot = new File(projectRootDir, 'app/build/intermediates/merged_native_libs')
        def readelfBin = new File(ndkRoot, 'toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-readelf')
        if (!readelfBin.exists()) readelfBin = llvmObjcopy.parentFile.toPath().resolve('llvm-readelf').toFile()

        def countPatched = 0
        def countAlreadyOk = 0
        mergedNativeRoot.eachFileRecurse(groovy.io.FileType.DIRECTORIES) { dir ->
            if (!dir.absolutePath.contains('/out/lib/')) return
            dir.eachFileMatch(~/.*libexpo-modules-core\\.so/) { so ->
                def tmp = new File(so.absolutePath + '.aligned')
                // BEFORE
                def alignBefore = 0
                if (readelfBin.exists()) {
                    def out = readelfBin.execute(['-lW', so.absolutePath], null).text
                    out.eachLine { line ->
                        if (line.trim().startsWith('LOAD')) {
                            def tok = line.trim().split()
                            if (tok.length >= 8) {
                                try { alignBefore = Math.max(alignBefore, Integer.parseInt(tok[7], 16)) } catch (ignored) {}
                            }
                        }
                    }
                }
                println "  alignExpoModulesCoreTo16K  ${so.name}  BEFORE align=${alignBefore == 0 ? '?' : '0x' + Integer.toHexString(alignBefore)}"
                if (alignBefore >= 0x4000) {
                    countAlreadyOk++
                    return
                }
                // Run llvm-objcopy --section-alignment 16384
                exec {
                    commandLine llvmObjcopy.absolutePath,
                        '--section-alignment', '16384',
                        so.absolutePath,
                        tmp.absolutePath
                }
                if (!tmp.exists() || tmp.length() == 0) {
                    throw new GradleException("llvm-objcopy failed to produce ${tmp}")
                }
                // Atomic move (Copy + Delete) so the file path stays the same for downstream tooling.
                java.nio.file.Files.move(
                    tmp.toPath(),
                    so.toPath(),
                    java.nio.file.StandardCopyOption.REPLACE_EXISTING,
                    java.nio.file.StandardCopyOption.ATOMIC_MOVE
                )
                // AFTER
                def alignAfter = 0
                if (readelfBin.exists()) {
                    def out2 = readelfBin.execute(['-lW', so.absolutePath], null).text
                    out2.eachLine { line ->
                        if (line.trim().startsWith('LOAD')) {
                            def tok = line.trim().split()
                            if (tok.length >= 8) {
                                try { alignAfter = Math.max(alignAfter, Integer.parseInt(tok[7], 16)) } catch (ignored) {}
                            }
                        }
                    }
                }
                println "  alignExpoModulesCoreTo16K  ${so.name}  AFTER  align=${alignAfter == 0 ? '?' : '0x' + Integer.toHexString(alignAfter)}"
                if (alignAfter < 0x4000) {
                    throw new GradleException("libexpo-modules-core.so still under-aligned after objcopy: ${so} (align=0x${Integer.toHexString(alignAfter)})")
                }
                countPatched++
            }
        }
        println "  alignExpoModulesCoreTo16K  patched=${countPatched}  already-16K=${countAlreadyOk}"
    }
}
afterEvaluate {
    tasks.named('bundleRelease').configure { dependsOn 'alignExpoModulesCoreTo16K' }
    tasks.named('assembleRelease').configure { dependsOn 'alignExpoModulesCoreTo16K' }
}
'''

# Append idempotently (so re-running patch_build_gradle.py on top of an
# already patched build.gradle doesn't stack the Gradle block).
existing = content
if 'tasks.register(\'alignExpoModulesCoreTo16K\')' in existing:
    ok('XVI — alignExpoModulesCoreTo16K task already injected; skipping')
    # Patch in-place if the task exists but lacks the dependsOn clause
    # (v1 of the task deferred dependsOn to afterEvaluate, which was a
    # race condition because the merged_native_libs directory did not
    # always exist by then → FileNotFoundException).
    patched = False
    if "dependsOn tasks.matching { it.name == 'mergeReleaseNativeLibs' }" not in existing:
        existing = existing.replace(
            "tasks.register('alignExpoModulesCoreTo16K') {\n    description = 'Re-align libexpo-modules-core.so segment LOAD to 16 KB for Play Console.'",
            "tasks.register('alignExpoModulesCoreTo16K') {\n    description = 'Re-align libexpo-modules-core.so segment LOAD to 16 KB for Play Console.'\n    dependsOn tasks.matching { it.name == 'mergeReleaseNativeLibs' }"
        )
        patched = True
        ok('XVI (in-place) — added dependsOn mergeReleaseNativeLibs')
    if patched:
        with open(gradle_path, 'w') as f:
            f.write(existing)
else:
    existing = existing + GROOVY_BLOCK
    with open(gradle_path, 'w') as f:
        f.write(existing)
    ok('XVI — alignExpoModulesCoreTo16K task injected into build.gradle')

# ── gradle.properties: idempotent R8 / ProGuard / 16 KB enforcement ─────────
# Removes ALL existing occurrences of each required key, then injects
# exactly ONE line with the correct value. Eliminates duplicate-key ambiguity
# (Gradle's findProperty behavior with multiple occurrences is non-deterministic).
props_path = PROPS_PATH
if os.path.exists(props_path):
    with open(props_path, 'r') as f:
        props = f.read()

    REQUIRED = {
        'android.enableProguardInReleaseBuilds':        'true',
        'android.enableShrinkResourcesInReleaseBuilds': 'true',
        'android.enableR8.fullMode':                    'true',
        'expo.useLegacyPackaging':                      'false',
        'android.bundle.enableUncompressedNativeLibs':  'true',
    }
    for key, val in REQUIRED.items():
        before = len(re.findall(rf'^{re.escape(key)}\s*=', props, re.MULTILINE))
        props = re.sub(rf'^{re.escape(key)}\s*=.*$', '', props, flags=re.MULTILINE)
        props += f'\n{key}={val}\n'
        info(f'  {key}: deduped ({before} → 1, value={val})')

    with open(props_path, 'w') as f:
        f.write(props)
    ok('gradle.properties rewritten (single-occurrence per required key)')
else:
    fail(f'⚠️  {props_path} missing')

# ── Copy proguard-rules.pro into android/app/ ───────────────────────────────
proguard_src = PROGUARD_SRC
proguard_dst = PROGUARD_DST
if os.path.exists(proguard_src):
    shutil.copy(proguard_src, proguard_dst)
    print(f'✅ proguard-rules.pro copied into {proguard_dst}')
else:
    fail(f'⚠️  proguard-rules.pro not found at {proguard_src}')

# ── FINAL STATE ASSERTIONS ──────────────────────────────────────────────────
# Read back files and verify every Play Console requirement is met. Fail loud.
print('\n── FINAL STATE ASSERTIONS ──────────────────────────────────')
with open(GRADLE_PATH) as f:
    final_gradle = f.read()
with open(PROPS_PATH) as f:
    final_props = f.read()

m_vc = re.search(r'versionCode\s+(\d+)', final_gradle)
m_vn = re.search(r'versionName\s+"([^"]+)"', final_gradle)


def count(key, text):
    return len(re.findall(rf'^{re.escape(key)}\s*=', text, re.MULTILINE))


checks = [
    ('build.gradle versionCode == app.json',
     m_vc and int(m_vc.group(1)) == target_vc,
     f'build.gradle={m_vc.group(1) if m_vc else "MISSING"} expected={target_vc}'),
    ('build.gradle versionName == app.json',
     m_vn and m_vn.group(1) == target_vn,
     f'build.gradle="{m_vn.group(1) if m_vn else "MISSING"}" expected="{target_vn}"'),
    ('build.gradle useLegacyPackaging = false (literal, 16 KB readiness)',
     re.search(r'^[ \t]*useLegacyPackaging\s+false[ \t]*$', final_gradle, re.MULTILINE) is not None,
     '`useLegacyPackaging false` line not present in build.gradle'),
    ('build.gradle alignExpoModulesCoreTo16K task registered (FILTER-SELECTIVE 16 KB fix)',
     "tasks.register('alignExpoModulesCoreTo16K')" in final_gradle,
     'alignExpoModulesCoreTo16K Gradle task not injected — libexpo-modules-core.so will stay 4 KB aligned and Play Console will still reject the AAB.'),
    ('build.gradle alignExpoModulesCoreTo16K wired into bundleRelease',
     "tasks.named('bundleRelease').configure { dependsOn 'alignExpoModulesCoreTo16K' }" in final_gradle,
     'alignExpoModulesCoreTo16K is not wired to bundleRelease — the post-link fix will not run before the AAB is built.'),
    ('release signingConfig present (with storeFile file(ksPath))',
     re.search(r'storeFile\s+file\(ksPath\)', final_gradle) is not None,
     '`storeFile file(ksPath)` not found — release signing config missing'),
    ('gradle.properties expo.useLegacyPackaging (count=1)',
     count('expo.useLegacyPackaging', final_props) == 1,
     f'count={count("expo.useLegacyPackaging", final_props)}, expected 1'),
    ('gradle.properties expo.useLegacyPackaging == false (16 KB readiness)',
     re.search(r'^expo\.useLegacyPackaging\s*=\s*false\s*$', final_props, re.MULTILINE) is not None,
     '`expo.useLegacyPackaging=false` not present in gradle.properties'),
    ('gradle.properties android.bundle.enableUncompressedNativeLibs == true',
     re.search(r'^android\.bundle\.enableUncompressedNativeLibs\s*=\s*true\s*$', final_props, re.MULTILINE) is not None,
     '`android.bundle.enableUncompressedNativeLibs=true` not present in gradle.properties'),
    ('gradle.properties android.enableR8.fullMode (count=1)',
     count('android.enableR8.fullMode', final_props) == 1,
     'expected exactly 1 occurrence'),
    ('gradle.properties android.enableProguardInReleaseBuilds (count=1)',
     count('android.enableProguardInReleaseBuilds', final_props) == 1,
     'expected exactly 1 occurrence'),
    ('gradle.properties android.enableShrinkResourcesInReleaseBuilds (count=1)',
     count('android.enableShrinkResourcesInReleaseBuilds', final_props) == 1,
     'expected exactly 1 occurrence'),
    ('ANDROID_KEYSTORE_PATH env var present',
     bool(os.environ.get('ANDROID_KEYSTORE_PATH')),
     'env var missing — release will fall back to debug.keystore!'),
    ('ANDROID_KEY_ALIAS env var present',
     bool(os.environ.get('ANDROID_KEY_ALIAS')),
     'env var missing — fallback alias `invoicestudio` will be used'),
]

for label, passed, detail in checks:
    icon = '✅' if passed else '❌'
    print(f'  {icon} {label}: {detail}')
    if not passed:
        FAILURES.append(f'{label}: {detail}')

if FAILURES:
    print(f'\n❌ patch_build_gradle.py FAILED — {len(FAILURES)} error(s):')
    for f in FAILURES:
        print(f'   • {f}')
    sys.exit(1)
else:
    print(f'\n✅ patch_build_gradle.py OK — v{target_vc} ({target_vn}) ready for Play Console.')
    sys.exit(0)
