#!/usr/bin/env python3
"""
Patches android/app/build.gradle (generated by expo prebuild) to add
a release signingConfig block and switch the release buildType to use it.

Environment variables consumed:
  ANDROID_KEYSTORE_PATH     – path to the keystore file (relative to android/app/)
  ANDROID_KEYSTORE_PASSWORD – store password
  ANDROID_KEY_ALIAS         – key alias
  ANDROID_KEY_PASSWORD      – key password
"""
import re
import os

gradle_path = os.path.join('android', 'app', 'build.gradle')

with open(gradle_path, 'r') as f:
    content = f.read()

release_block = '''
        release {
            def ksPath = System.getenv("ANDROID_KEYSTORE_PATH") ?: "debug.keystore"
            def ksPass = System.getenv("ANDROID_KEYSTORE_PASSWORD") ?: "android"
            def kAlias = System.getenv("ANDROID_KEY_ALIAS") ?: "invoicestudio"
            def kPass  = System.getenv("ANDROID_KEY_PASSWORD") ?: "android"
            storeFile file(ksPath)
            storePassword ksPass
            keyAlias kAlias
            keyPassword kPass
        }'''

# Insert release block after the closing brace of the debug signingConfig
content = re.sub(
    r"(keyPassword 'android'\n        \})\n    \}\n    buildTypes",
    r"\g<1>" + release_block + "\n    }\n    buildTypes",
    content
)

# Switch release buildType to use release signingConfig
content = content.replace(
    "signingConfig signingConfigs.debug\n            shrinkResources",
    "signingConfig signingConfigs.release\n            shrinkResources"
)

with open(gradle_path, 'w') as f:
    f.write(content)

print('✅ build.gradle patched for release signing')
