#!/usr/bin/env python3
"""
Patches android/app/build.gradle (generated by expo prebuild) to add
a release signingConfig block and switch the release buildType to use it.

Also enables ProGuard for release builds and writes proguard-rules.pro
with React Native safe rules.

Environment variables consumed:
  ANDROID_KEYSTORE_PATH     – path to the keystore file (relative to android/app/)
  ANDROID_KEYSTORE_PASSWORD – store password
  ANDROID_KEY_ALIAS         – key alias
  ANDROID_KEY_PASSWORD      – key password
"""
import re
import os
import shutil

gradle_path = os.path.join('android', 'app', 'build.gradle')

with open(gradle_path, 'r') as f:
    content = f.read()

release_block = '''
        release {
            def ksPath = System.getenv("ANDROID_KEYSTORE_PATH") ?: "debug.keystore"
            def ksPass = System.getenv("ANDROID_KEYSTORE_PASSWORD") ?: "android"
            def kAlias = System.getenv("ANDROID_KEY_ALIAS") ?: "invoicestudio"
            def kPass  = System.getenv("ANDROID_KEY_PASSWORD") ?: "android"
            storeFile file(ksPath)
            storePassword ksPass
            keyAlias kAlias
            keyPassword kPass
        }'''

# Insert release block after the closing brace of the debug signingConfig
content = re.sub(
    r"(keyPassword 'android'\n        \})\n    \}\n    buildTypes",
    r"\g<1>" + release_block + "\n    }\n    buildTypes",
    content
)

# Switch release buildType to use release signingConfig
content = content.replace(
    "signingConfig signingConfigs.debug\n            shrinkResources",
    "signingConfig signingConfigs.release\n            shrinkResources"
)

with open(gradle_path, 'w') as f:
    f.write(content)

print('✅ build.gradle patched for release signing')

# ── Enable ProGuard/R8 in gradle.properties ──────────────────────────────────
props_path = os.path.join('android', 'gradle.properties')
if os.path.exists(props_path):
    with open(props_path, 'r') as f:
        props = f.read()
    # Set enableProguardInReleaseBuilds to true
    props = re.sub(
        r'android\.enableProguardInReleaseBuilds\s*=\s*.*',
        'android.enableProguardInReleaseBuilds=true',
        props
    )
    # If the line doesn't exist, append it
    if 'android.enableProguardInReleaseBuilds' not in props:
        props += '\nandroid.enableProguardInReleaseBuilds=true\n'
    with open(props_path, 'w') as f:
        f.write(props)
    print('✅ gradle.properties updated: ProGuard enabled for release')
else:
    print('⚠️  android/gradle.properties not found, skipping ProGuard enable')

# ── Copy proguard-rules.pro into android/app/ ─────────────────────────────────
proguard_src = os.path.join('..', 'proguard-rules.pro')
proguard_dst = os.path.join('android', 'app', 'proguard-rules.pro')
if os.path.exists(proguard_src):
    shutil.copy(proguard_src, proguard_dst)
    print('✅ proguard-rules.pro copied into android/app/')
else:
    print('⚠️  proguard-rules.pro not found in mobile/, skipping')
